// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqklHyDrhhAvcDCR-IL84AWBFCA05b2U',
    appId: '1:1095657647910:web:654288cdb8d206ecfe5be7',
    messagingSenderId: '1095657647910',
    projectId: 'last-set-fit',
    authDomain: 'last-set-fit.firebaseapp.com',
    storageBucket: 'last-set-fit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFoJgAK0HaKrU1ViqDGf8mcU3xo4GhX98',
    appId: '1:1095657647910:android:24ddf62bea44b445fe5be7',
    messagingSenderId: '1095657647910',
    projectId: 'last-set-fit',
    storageBucket: 'last-set-fit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOuciGDr836iRBLXPlahyWowa8Pc8IF50',
    appId: '1:1095657647910:ios:1593257e5b04ea51fe5be7',
    messagingSenderId: '1095657647910',
    projectId: 'last-set-fit',
    storageBucket: 'last-set-fit.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOuciGDr836iRBLXPlahyWowa8Pc8IF50',
    appId: '1:1095657647910:ios:1593257e5b04ea51fe5be7',
    messagingSenderId: '1095657647910',
    projectId: 'last-set-fit',
    storageBucket: 'last-set-fit.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVqklHyDrhhAvcDCR-IL84AWBFCA05b2U',
    appId: '1:1095657647910:web:c7a43707ac12ca4cfe5be7',
    messagingSenderId: '1095657647910',
    projectId: 'last-set-fit',
    authDomain: 'last-set-fit.firebaseapp.com',
    storageBucket: 'last-set-fit.appspot.com',
  );
}
